### ISSUE TITLE
No binary

### ISSUE THREAD

**Issue by gerroon** [nefarius/WindowsLayoutSnapshot#1]
Hi

it does not look like there is any binary executable file in the latest release.

Thanks

**Comment by mayerwin** [comment]
Just compiled it:
[WindowsLayoutSnapshot.zip](https://github.com/nefarius/WindowsLayoutSnapshot/files/4364872/WindowsLayoutSnapshot.zip)

**Comment by nefarius** [comment]
Didn't see this one for 3 years, that is dedication 😬

**Comment by nefarius** [comment]
Released 🥳
